### ISSUE TITLE
[Nav] 네비게이션 바 및 Redux로 사용자 정보 관리 구현 1차

### ISSUE THREAD

**Issue by nusuy** [GDSC-SWU/2022-02-web-dev-toy-project-fe#3]
## TODO
- Redux로 사용자 정보 관리
    - [x] access token, 닉네임 저장
    - [x] local storage에 저장 (redux-persist)
    - [x] 로그인 정보 반영 함수 구현 (`setUserInfo`)
-  네비게이션 바 구현
    - [x] 항상 상단 고정, 라우터로 다른 컴포넌트 이동
    - [x] Redux-store의 state에 따라 네비게이션 바에 보여지는 정보 달라짐
- 메인 페이지(홈) 구현
    - [x] 상단 검색 바 (`SearchBar`)
    - [x] 하단 네비게이션 바 (`NavBar`)
